services:
  - type: web
    name: calculator-hub
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
