"""
Default KaTeX-formatted SEO educational articles for Batch #13 Calculators.
Each article contains comprehensive, academic, 400+ word guides with LaTeX formulas.
"""

ANNUITY_PAYOUT_ARTICLE = r"""
<div class="article-content">
    <h2>Actuarial Mathematics of Annuity Payouts & Capital Decumulation</h2>
    <p>
        An <strong>annuity</strong> is a legal contract issued by a financial institution or life insurance company designed to accept, invest, and systematically liquidate funds to provide a guaranteed periodic income stream. In modern wealth management and retirement decumulation, an annuity transforms a lump-sum nest egg (present value $PV$) into an orderly series of predictable cash flows ($PMT$) across a defined planning horizon or the annuitant's remaining lifespan.
    </p>

    <h3>Mathematical Formulation of Fixed Period Annuities</h3>
    <p>
        The periodic distribution payment $PMT$ derived from an initial principal balance $P$ at an annualized nominal interest rate $r$, compounded across $m$ distribution cycles per calendar year over $t$ years (yielding $n = m \cdot t$ total payout periods and a periodic discount rate $i = \frac{r}{m}$), is governed by the discounted present value of an ordinary annuity:
    </p>
    <p>
        $$P = PMT \cdot \left[ \frac{1 - (1 + i)^{-n}}{i} \right]$$
    </p>
    <p>
        Solving for the periodic payout disbursement $PMT$:
    </p>
    <p>
        $$PMT = \frac{P \cdot i}{1 - (1 + i)^{-n}}$$
    </p>

    <h3>Ordinary Annuity vs. Annuity Due Cash Flow Timing</h3>
    <p>
        The timing of each cash flow fundamentally alters interest accrual within each compounding interval:
    </p>
    <ul>
        <li>
            <strong>Ordinary Annuity (Arrears):</strong> Payouts occur at the end of each payment period (e.g., end of the month). Because the balance generates interest over the entire first period before any capital is withdrawn, the standard formula applies directly:
            $$PMT_{\text{ordinary}} = \frac{P \cdot i}{1 - (1 + i)^{-n}}$$
        </li>
        <li>
            <strong>Annuity Due (Advance):</strong> Payouts occur immediately at the start of each interval (e.g., first day of the month). Because the initial withdrawal reduces the earning principal on day zero, each payment experiences an additional period of compound growth:
            $$PMT_{\text{due}} = \frac{PMT_{\text{ordinary}}}{1 + i} = \frac{P \cdot i}{(1 + i) \cdot \left[ 1 - (1 + i)^{-n} \right]}$$
        </li>
    </ul>

    <h3>Portfolio Longevity: Solving for Exhaustion Duration</h3>
    <p>
        When an annuitant specifies a target fixed periodic withdrawal amount $PMT$ rather than a fixed term, the question shifts to: <em>How long will the principal survive?</em>
    </p>
    <p>
        Isolating the number of compounding periods $n$ from the present value equation yields the logarithmic decumulation formula:
    </p>
    <p>
        $$n = -\frac{\ln\left(1 - \frac{P \cdot i}{PMT}\right)}{\ln(1 + i)}$$
    </p>
    <p>
        <strong>The Infinite Capital Threshold (Perpetuity):</strong> Notice that the term within the natural logarithm must satisfy $1 - \frac{P \cdot i}{PMT} > 0$. If the withdrawal amount is less than or equal to the interest generated in a single period ($PMT \le P \cdot i$), the principal balance is never depleted ($n \to \infty$). Under this equilibrium, the fund operates as a perpetuity generating sustainable cash flow indefinitely without encroaching on the underlying endowment.
    </p>

    <h3>Total Return & Aggregate Interest Computation</h3>
    <p>
        Over the complete lifecycle of a term annuity, the cumulative payout received by the investor ($R_{\text{total}}$) and the aggregate interest generated by the declining principal balance ($I_{\text{total}}$) are quantified by:
    </p>
    <p>
        $$R_{\text{total}} = n \cdot PMT$$
    </p>
    <p>
        $$I_{\text{total}} = R_{\text{total}} - P = (n \cdot PMT) - P$$
    </p>

    <h3>Inflation Risk & Real Purchasing Power Erosion</h3>
    <p>
        While fixed nominal payouts guarantee steady monetary figures, general macroeconomic inflation ($\pi$) progressively erodes real purchasing power. The inflation-adjusted real value $PMT_{\text{real}}$ of a payment received at year $k$ is given by:
    </p>
    <p>
        $$PMT_{\text{real}}(k) = \frac{PMT_{\text{nominal}}}{(1 + \pi)^k}$$
    </p>
    <p>
        For instance, at a persistent annual inflation rate of $3.0\%$, a fixed monthly payout of $\$2,500$ loses over $35\%$ of its functional purchasing utility by Year 15, highlighting the critical imperative of integrating cost-of-living adjustment riders (COLA) or maintaining equity-buffered growth allocations alongside fixed annuity commitments.
    </p>
</div>
"""

ARMY_BODY_FAT_ARTICLE = r"""
<div class="article-content">
    <h2>US Army Body Composition Program (AR 600-9) Tape Test Science</h2>
    <p>
        The <strong>United States Army Body Composition Program (AR 600-9)</strong> establishes military readiness standards designed to ensure operational physical fitness, cardiovascular endurance, and military bearing across all active-duty, reserve, and National Guard service members. When a soldier exceeds the screening weight-for-height tables, the Department of Defense mandates an objective anthropometric circumference assessment commonly referred to as the <em>Army Tape Test</em>.
    </p>

    <h3>Official Department of Defense Anthropometric Equations</h3>
    <p>
        The Department of Defense anthropometric body fat algorithms were developed by researchers at the Naval Health Research Center (Hodgdon &amp; Beckett, 1984) and codified in Department of Defense Instruction (DoDI) 1308.3. The mathematical models correlate circumferential body measurements with body density ($\rho$) established through hydrostatic underwater weighing.
    </p>

    <h4>Male Body Fat Formulation</h4>
    <p>
        For male service members, body fat percentage $(\%BF_{\text{male}})$ is computed from measured height, neck circumference, and abdominal circumference (measured at the level of the navel):
    </p>
    <p>
        $$\%BF_{\text{male}} = 86.010 \cdot \log_{10}(\text{waist} - \text{neck}) - 70.041 \cdot \log_{10}(\text{height}) + 36.76$$
    </p>
    <p>
        <em>Note:</em> All circumference and height measurements in the empirical constants are calibrated in inches. For metric measurements, values must be converted via $1\text{ in} = 2.54\text{ cm}$.
    </p>

    <h4>Female Body Fat Formulation</h4>
    <p>
        For female service members, the formula incorporates an additional pelvic anatomical site (hip circumference at the greatest horizontal protrusion of the buttocks) to account for gynoid adiposity distribution:
    </p>
    <p>
        $$\%BF_{\text{female}} = 163.205 \cdot \log_{10}(\text{waist} + \text{hip} - \text{neck}) - 97.684 \cdot \log_{10}(\text{height}) - 78.387$$
    </p>

    <h3>Standard Regulatory Screening Limits by Age Bracket</h3>
    <p>
        Army Regulation 600-9 mandates progressive allowable body fat thresholds that increase with chronological age to accommodate natural physiological and hormonal adaptations over a military career:
    </p>
    <ul>
        <li><strong>Ages 17 to 20:</strong> Maximum allowable body fat is $20.0\%$ for males and $30.0\%$ for females.</li>
        <li><strong>Ages 21 to 27:</strong> Maximum allowable body fat is $22.0\%$ for males and $32.0\%$ for females.</li>
        <li><strong>Ages 28 to 39:</strong> Maximum allowable body fat is $24.0\%$ for males and $34.0\%$ for females.</li>
        <li><strong>Ages 40 and older:</strong> Maximum allowable body fat is $26.0\%$ for males and $36.0\%$ for females.</li>
    </ul>

    <h3>Standardized Measurement Technique & Tape Protocol</h3>
    <p>
        Accuracy and reproducibility in AR 600-9 compliance rely on strict execution protocol:
    </p>
    <ul>
        <li><strong>Measuring Tape:</strong> Must be non-stretchable fiberglass calibrated in inches or quarter-inches, applied with uniform tension without compressing soft subcutaneous tissue.</li>
        <li><strong>Height:</strong> Measured without footwear on a flat, level surface, with the soldier standing erect in the military position of attention.</li>
        <li><strong>Neck:</strong> Measured directly below the larynx (thyroid cartilage / Adam's apple), with the tape perpendicular to the long axis of the neck.</li>
        <li><strong>Waist (Abdomen):</strong> For males, measured horizontally across the navel (umbilicus) at the end of normal expiration. For females, measured at the narrowest point of the torso (natural waist) or midway between the lower costal rib margin and the iliac crest.</li>
        <li><strong>Hips (Females Only):</strong> Measured horizontally around the widest prominence of the buttocks viewed from the lateral aspect.</li>
    </ul>

    <h3>Body Mass Partitioning: Lean Mass vs. Fat Mass</h3>
    <p>
        Given total body weight $W_{\text{total}}$, total adipose fat mass ($M_{\text{fat}}$) and fat-free lean body mass ($M_{\text{lean}}$) are derived as:
    </p>
    <p>
        $$M_{\text{fat}} = W_{\text{total}} \times \left( \frac{\%BF}{100} \right)$$
    </p>
    <p>
        $$M_{\text{lean}} = W_{\text{total}} - M_{\text{fat}} = W_{\text{total}} \times \left( 1 - \frac{\%BF}{100} \right)$$
    </p>
    <p>
        To regain compliance when exceeding regulatory limits, a soldier must create a sustained caloric deficit while preserving lean muscle tissue through progressive resistance training, reducing the waist-to-neck differential to achieve the target logarithmic ratio.
    </p>
</div>
"""

MEAN_MEDIAN_MODE_ARTICLE = r"""
<div class="article-content">
    <h2>Measures of Central Tendency & Statistical Dispersion Analysis</h2>
    <p>
        In descriptive statistics and exploratory data analysis (EDA), <strong>measures of central tendency</strong> identify the central or typical value around which an empirical dataset clusters. Complementary <strong>measures of dispersion</strong> quantify the extent of variation, scatter, or spread within the distribution. Together, these metrics summarize complex multidimensional datasets into intuitive analytical parameters.
    </p>

    <h3>1. The Arithmetic Mean ($\bar{x}$ and $\mu$)</h3>
    <p>
        The <strong>mean</strong> is the mathematical average of all observations in a dataset. For a sample of $n$ observations $\{x_1, x_2, \dots, x_n\}$, the sample mean $\bar{x}$ is defined as:
    </p>
    <p>
        $$\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i = \frac{x_1 + x_2 + \dots + x_n}{n}$$
    </p>
    <p>
        For an entire population containing $N$ elements, the population mean $\mu$ shares the identical algebraic formulation with denominator $N$. The mean possesses the mathematical property that the sum of deviations of all observations from the mean is identically zero: $\sum_{i=1}^n (x_i - \bar{x}) = 0$. However, the arithmetic mean is highly sensitive to extreme outliers and asymmetric skewness.
    </p>

    <h3>2. The Median ($M$ or $\tilde{x}$)</h3>
    <p>
        The <strong>median</strong> is the positional middle value when the data elements are sorted in ascending numerical order ($x_{(1)} \le x_{(2)} \le \dots \le x_{(n)}$). It divides the probability distribution exactly into equal halves ($50\%$ below, $50\%$ above):
    </p>
    <ul>
        <li>
            <strong>Odd Sample Size ($n$ is odd):</strong> The median occupies the exact central position $k = \frac{n + 1}{2}$:
            $$M = x_{\left( \frac{n+1}{2} \right)}$$
        </li>
        <li>
            <strong>Even Sample Size ($n$ is even):</strong> The median is the arithmetic average of the two central order statistics:
            $$M = \frac{x_{\left(\frac{n}{2}\right)} + x_{\left(\frac{n}{2} + 1\right)}}{2}$$
        </li>
    </ul>
    <p>
        Because the median depends solely on rank order rather than numerical magnitudes at the extremes, it is a <em>robust statistic</em> exhibiting high resistance against extreme outliers.
    </p>

    <h3>3. The Mode ($Mo$) & Multimodality</h3>
    <p>
        The <strong>mode</strong> is the data value or values that appear with the highest frequency within the dataset. A dataset may exhibit diverse modal characteristics:
    </p>
    <ul>
        <li><strong>Unimodal:</strong> A unique value appears with the maximum frequency.</li>
        <li><strong>Bimodal / Multimodal:</strong> Two or more distinct values share the identical maximum frequency.</li>
        <li><strong>No Mode:</strong> Every element in the dataset occurs with identical frequency (e.g., all elements unique).</li>
    </ul>

    <h3>Distribution Skewness & Relationship Between Metrics</h3>
    <p>
        The relative geometric alignment of mean, median, and mode serves as a diagnostic indicator of distributional symmetry:
    </p>
    <ul>
        <li><strong>Symmetric (Normal / Gaussian):</strong> $\text{Mean} \approx \text{Median} \approx \text{Mode}$. The distribution displays a bell curve with zero skewness.</li>
        <li><strong>Positive Skew (Right-Skewed):</strong> $\text{Mode} < \text{Median} < \text{Mean}$. Long upper tail; extreme high values pull the mean upward.</li>
        <li><strong>Negative Skew (Left-Skewed):</strong> $\text{Mean} < \text{Median} < \text{Mode}$. Long lower tail; extreme low values pull the mean downward.</li>
    </ul>

    <h3>Measures of Statistical Dispersion & Variability</h3>
    <p>
        To gauge the spread around central tendency, statistical dispersion metrics are calculated:
    </p>
    <ul>
        <li><strong>Range:</strong> $R = x_{\max} - x_{\min}$, measuring the total span of values.</li>
        <li>
            <strong>Sample Variance ($s^2$):</strong> Incorporates <em>Bessel's correction</em> ($n-1$ degrees of freedom) to ensure an unbiased estimator of population variance:
            $$s^2 = \frac{1}{n - 1} \sum_{i=1}^n (x_i - \bar{x})^2$$
        </li>
        <li>
            <strong>Population Variance ($\sigma^2$):</strong> Uses total population count $N$:
            $$\sigma^2 = \frac{1}{N} \sum_{i=1}^N (x_i - \mu)^2$$
        </li>
        <li>
            <strong>Standard Deviation ($s$ and $\sigma$):</strong> The square root of variance, restoring variability into the original units of measurement:
            $$s = \sqrt{s^2}, \quad \sigma = \sqrt{\sigma^2}$$
        </li>
        <li>
            <strong>Interquartile Range ($IQR$):</strong> The distance between the 75th percentile ($Q_3$) and the 25th percentile ($Q_1$), $IQR = Q_3 - Q_1$, representing the spread of the central $50\%$ of observations.
        </li>
    </ul>
</div>
"""

POWER_CONVERTER_ARTICLE = r"""
<div class="article-content">
    <h2>Physics of Power, Energy Transfer Rates & Unit Conversion Mechanics</h2>
    <p>
        In classical physics and engineering, <strong>power</strong> is the quantitative rate at which work ($W$) is performed or energy ($E$) is transferred, transformed, or consumed per unit of time ($t$). As a fundamental scalar quantity in the International System of Units (SI), power bridges mechanical dynamics, electrical circuit theory, fluid kinetics, and thermodynamic heat transfer.
    </p>

    <h3>Fundamental Physical Definitions of Power</h3>
    <p>
        Power represents the first time derivative of work done or energy transformed:
    </p>
    <p>
        $$P = \frac{dW}{dt} = \frac{dE}{dt}$$
    </p>
    <p>
        In diverse engineering domains, this general derivative manifests in specific formulations:
    </p>
    <ul>
        <li>
            <strong>Translational Mechanics:</strong> For a constant or instantaneous force $\vec{F}$ acting on a body traveling at velocity $\vec{v}$:
            $$P = \vec{F} \cdot \vec{v} = F \cdot v \cdot \cos(\theta)$$
        </li>
        <li>
            <strong>Rotational Machinery:</strong> For an applied shaft torque $\tau$ rotating at angular velocity $\omega$ (radians per second):
            $$P = \tau \cdot \omega = \frac{2\pi \cdot N \cdot \tau}{60}$$
            where $N$ is revolutions per minute (RPM).
        </li>
        <li>
            <strong>Electrical Power (Joule's Law):</strong> In direct current (DC) or resistive alternating current (AC) with voltage $V$ and electric current $I$:
            $$P = V \cdot I = I^2 R = \frac{V^2}{R}$$
        </li>
        <li>
            <strong>Thermal Heat Flux:</strong> Rate of heat transfer $Q$ across a thermal gradient:
            $$P = \dot{Q} = \frac{dQ}{dt}$$
        </li>
    </ul>

    <h3>The SI Base Unit: The Watt (W)</h3>
    <p>
        The coherent SI unit of power is the <strong>Watt</strong> ($W$), named in honor of Scottish engineer James Watt. One watt represents the expenditure of one joule of energy over the duration of one second:
    </p>
    <p>
        $$1\text{ W} = 1\text{ J/s} = 1\text{ kg}\cdot\text{m}^2\cdot\text{s}^{-3} = 1\text{ N}\cdot\text{m/s} = 1\text{ V}\cdot\text{A}$$
    </p>

    <h3>Mechanical Horsepower: Origin & Modern Standards</h3>
    <p>
        In the late 18th century, James Watt created the concept of <strong>horsepower</strong> ($hp$) to market his improved steam engines to coal mine operators by comparing mechanical output to draft pit ponies:
    </p>
    <ul>
        <li>
            <strong>Imperial / Mechanical Horsepower ($hp$ or $hp(I)$):</strong> Defined as exactly $550\text{ foot-pounds force per second}$ ($550\text{ ft}\cdot\text{lbf/s}$):
            $$1\text{ hp} = 550\text{ ft}\cdot\text{lbf/s} = 33,000\text{ ft}\cdot\text{lbf/min} \approx 745.699872\text{ W}$$
        </li>
        <li>
            <strong>Metric Horsepower ($PS$, $cv$, $pk$, $ch$):</strong> Adopted in continental Europe (German <em>Pferdestärke</em>) defined as the power required to raise a $75\text{ kg}$ mass against Earth standard gravity ($9.80665\text{ m/s}^2$) by $1\text{ meter}$ in $1\text{ second}$:
            $$1\text{ PS} = 75\text{ kgf}\cdot\text{m/s} = 75 \times 9.80665 \approx 735.49875\text{ W}$$
        </li>
        <li>
            <strong>Electrical Horsepower ($hp(E)$):</strong> Used by electrical equipment manufacturers and the National Electrical Code (NEC), defined as exactly $746\text{ W}$.
        </li>
    </ul>

    <h3>Thermal & HVAC Power Units</h3>
    <p>
        Thermal engineering, air conditioning, and refrigeration utilize distinct historical units:
    </p>
    <ul>
        <li>
            <strong>British Thermal Unit per Hour ($BTU/h$):</strong> Defined as the rate of heat needed to raise the temperature of one pound of liquid water by $1^\circ\text{F}$ per hour:
            $$1\text{ BTU/h} \approx 0.29307107\text{ W}, \quad 1\text{ kW} \approx 3,412.142\text{ BTU/h}$$
        </li>
        <li>
            <strong>Ton of Refrigeration ($TR$):</strong> The cooling power required to freeze $1\text{ short ton}$ ($2,000\text{ lbs}$) of pure water at $0^\circ\text{C}$ into ice in $24\text{ hours}$ (latent heat of fusion of ice $= 144\text{ BTU/lb}$):
            $$1\text{ TR} = \frac{2000 \times 144\text{ BTU}}{24\text{ h}} = 12,000\text{ BTU/h} \approx 3,516.85284\text{ W} = 3.517\text{ kW}$$
        </li>
    </ul>

    <h3>Logarithmic Power Units in Telecommunications & RF ($dBm$ and $dBW$)</h3>
    <p>
        In telecommunications, wireless acoustics, and radio-frequency (RF) engineering, power varies over tens of orders of magnitude. Engineers utilize logarithmic decibel scales referenced to standard base thresholds:
    </p>
    <p>
        $$P_{\text{dBm}} = 10 \cdot \log_{10}\left( \frac{P_{\text{Watts}}}{1\text{ mW}} \right) = 10 \cdot \log_{10}(P_{\text{Watts}} \times 1000)$$
    </p>
    <p>
        $$P_{\text{dBW}} = 10 \cdot \log_{10}\left( \frac{P_{\text{Watts}}}{1\text{ W}} \right) = P_{\text{dBm}} - 30$$
    </p>
    <p>
        For instance, $0\text{ dBm} = 1\text{ mW}$, $30\text{ dBm} = 1\text{ W}$, and $60\text{ dBm} = 1\text{ kW}$.
    </p>
</div>
"""
