"""
Default educational articles for Batch #11 calculators.
All articles exceed 400 words and incorporate professional KaTeX mathematical formulas.
"""

CD_ARTICLE = r"""
<article class="calculator-article">
    <h2>The Mathematics of Certificate of Deposit (CD) Instruments &amp; Compounding Mechanics</h2>
    <p>
        A Certificate of Deposit (CD) is a federally insured, time-deposit financial contract issued by commercial banks and credit unions. Under this promissory instrument, a depositor commits an initial principal sum $P$ for a predetermined fixed tenure (ranging from 1 month to 10 years) in exchange for a guaranteed nominal interest rate $r$ or Annual Percentage Yield ($\text{APY}$). Unlike demand deposit accounts or high-yield savings vehicles, CDs operate under strict maturity covenants: early capital withdrawal before the agreed settlement date triggers statutory forfeiture penalties.
    </p>

    <h3>Discrete Compounding &amp; Nominal vs. Effective Annual Yield</h3>
    <p>
        The future valuation $A(t)$ of a CD deposit compounded at discrete intervals $n$ times per annum over $t$ years is governed by the classical compound accretion model:
    </p>
    <div class="math-display">
        $$A(t) = P \left(1 + \frac{r}{n}\right)^{n \cdot t}$$
    </div>
    <p>
        Where $P$ represents the initial principal, $r$ is the nominal annualized interest rate expressed as a decimal, $n$ is the compounding frequency per calendar year (e.g., $n = 365$ for daily, $n = 12$ for monthly, $n = 4$ for quarterly, $n = 1$ for annual compounding), and $t$ is the elapsed duration in years.
    </p>
    <p>
        To standardize comparative disclosures under the United States Truth in Savings Act (Regulation DD), financial institutions must report the <strong>Annual Percentage Yield ($\text{APY}$)</strong>. The $\text{APY}$ captures the compounding effect over an entire 365-day year:
    </p>
    <div class="math-display">
        $$\text{APY} = \left(1 + \frac{r}{n}\right)^n - 1 \iff r = n \left[\left(1 + \text{APY}\right)^{\frac{1}{n}} - 1\right]$$
    </div>
    <p>
        When an institution quotes an $\text{APY}$ directly, the terminal balance at maturity $T$ years can be expressed simply as:
    </p>
    <div class="math-display">
        $$A = P \left(1 + \text{APY}\right)^t$$
    </div>

    <h3>Continuous Compounding Limit</h3>
    <p>
        As the compounding frequency approaches infinity ($n \to \infty$), the terminal account balance converges to the exponential boundary defined by Euler's constant $e$:
    </p>
    <div class="math-display">
        $$\lim_{n \to \infty} P \left(1 + \frac{r}{n}\right)^{nt} = P \cdot e^{rt}$$
    </div>

    <h3>Early Withdrawal Penalty (EWP) Mechanics</h3>
    <p>
        When an investor liquidates a CD prior to contract maturity, banks assess an Early Withdrawal Penalty ($\text{EWP}$). Statutory penalties are typically quantified as $k$ months of simple or compound interest. Let $k$ be the penalty period in months:
    </p>
    <div class="math-display">
        $$\text{Penalty}_{\text{simple}} = P \times \left(\frac{r}{12}\right) \times k$$
    </div>
    <p>
        If the total earned interest $I_{\text{earned}} = A(t) - P$ at the moment of premature liquidation is less than the computed penalty ($\text{Penalty} > I_{\text{earned}}$), the deficit is deducted directly from the depositor's principal balance $P$, yielding a net negative nominal return.
    </p>

    <h3>Tax Drag &amp; After-Tax Real Yield</h3>
    <p>
        Interest generated by certificates of deposit is categorized as ordinary taxable income at both federal and state jurisdictional levels in the year it accrues, regardless of whether funds are withdrawn or rolled over. If an investor faces a marginal tax rate $\tau_{\text{tax}}$ and an annualized inflation rate $i$, the nominal after-tax rate $r_{\text{after}}$ and Fisher real rate $r_{\text{real}}$ are formulated as:
    </p>
    <div class="math-display">
        $$r_{\text{after}} = \text{APY} \times \left(1 - \tau_{\text{tax}}\right)$$
    </div>
    <div class="math-display">
        $$r_{\text{real}} = \frac{1 + r_{\text{after}}}{1 + i} - 1 \approx r_{\text{after}} - i$$
    </div>

    <h3>Strategic CD Laddering Optimization</h3>
    <p>
        To mitigate interest rate duration risk and maintain liquidity without triggering early withdrawal penalties, fixed-income investors deploy <strong>CD Laddering</strong>. By distributing total capital $C_{\text{total}}$ equally across $m$ tranches with staggered maturities ($1, 2, 3, \dots, m$ years), one tranche matures every period, creating continuous liquidity while capturing longer-term yields.
    </p>
</article>
"""

MACRO_ARTICLE = r"""
<article class="calculator-article">
    <h2>Nutritional Bioenergetics: The Science of Macronutrient Ratios &amp; Metabolic Partitioning</h2>
    <p>
        Macronutrients—proteins, carbohydrates, and dietary lipids—constitute the energetic and structural substrates that sustain human homeostasis, cellular regeneration, and physical performance. While total caloric equilibrium determines gross body mass fluctuations according to the first law of thermodynamics, the quantitative distribution of macronutrients governs body composition partitioning: the selective accretion or oxidation of fat-free mass (skeletal muscle) versus adipose tissue.
    </p>

    <h3>Metabolic Energy Equivalents (Atwater General Factors)</h3>
    <p>
        Nutritional bioenergetics relies on the classical Atwater physiological fuel values, which represent the net metabolizable energy yielded per gram of combusted substrate after accounting for gastrointestinal absorption efficiency and obligatory urinary nitrogen excretion:
    </p>
    <ul class="article-list">
        <li><strong>Proteins:</strong> $4.0\ \text{kcal/g}$ ($16.7\ \text{kJ/g}$) with a thermic effect of feeding ($\text{TEF}$) of $20\text{--}30\%$.</li>
        <li><strong>Carbohydrates:</strong> $4.0\ \text{kcal/g}$ ($16.7\ \text{kJ/g}$) with a $\text{TEF}$ of $5\text{--}10\%$.</li>
        <li><strong>Lipids (Fats):</strong> $9.0\ \text{kcal/g}$ ($37.7\ \text{kJ/g}$) with a $\text{TEF}$ of $0\text{--}3\%$.</li>
    </ul>

    <h3>Basal Metabolic Rate ($\text{BMR}$) Estimation</h3>
    <p>
        The gold standard clinical model for estimating Basal Metabolic Rate ($\text{BMR}$) in healthy populations is the <strong>Mifflin-St Jeor equation</strong>, validated against indirect calorimetry:
    </p>
    <div class="math-display">
        $$\text{BMR}_{\text{male}} = 10 \cdot m + 6.25 \cdot h - 5 \cdot a + 5$$
    </div>
    <div class="math-display">
        $$\text{BMR}_{\text{female}} = 10 \cdot m + 6.25 \cdot h - 5 \cdot a - 161$$
    </div>
    <p>
        Where $m$ is body mass in kilograms, $h$ is standing height in centimeters, and $a$ is biological age in years.
    </p>

    <h3>Total Daily Energy Expenditure ($\text{TDEE}$) &amp; Target Calories</h3>
    <p>
        Total Daily Energy Expenditure ($\text{TDEE}$) scales $\text{BMR}$ through a physical activity level factor ($\text{PAL}$):
    </p>
    <div class="math-display">
        $$\text{TDEE} = \text{BMR} \times \text{PAL}$$
    </div>
    <p>
        Where $\text{PAL} \in [1.2, 1.9]$ ranges from sedentary desk lifestyles ($\text{PAL} = 1.2$) to competitive athletic conditioning ($\text{PAL} = 1.9$). Target caloric intake $C_{\text{target}}$ is subsequently modulated based on physiological goals:
    </p>
    <div class="math-display">
        $$C_{\text{target}} = \text{TDEE} \times (1 + \Delta_{\text{goal}})$$
    </div>
    <p>
        Where $\Delta_{\text{goal}} = -0.20$ for accelerated fat loss (20% deficit), $\Delta_{\text{goal}} = -0.10$ for moderate cutting, $\Delta_{\text{goal}} = 0$ for weight maintenance, and $\Delta_{\text{goal}} = +0.10\text{ to }+0.15$ for lean hypercaloric muscular hypertrophy.
    </p>

    <h3>Mathematical Formulation of Substrate Gram Partitioning</h3>
    <p>
        Given target daily calories $C_{\text{target}}$ and desired percentage allocations for protein ($P_{\%}$), carbohydrate ($C_{\%}$), and fat ($F_{\%}$) such that $P_{\%} + C_{\%} + F_{\%} = 100\%$, the daily mass of each nutrient in grams is derived analytically:
    </p>
    <div class="math-display">
        $$m_{\text{protein}} = \frac{C_{\text{target}} \cdot P_{\%}}{4\ \text{kcal/g}}$$
    </div>
    <div class="math-display">
        $$m_{\text{carb}} = \frac{C_{\text{target}} \cdot C_{\%}}{4\ \text{kcal/g}}$$
    </div>
    <div class="math-display">
        $$m_{\text{fat}} = \frac{C_{\text{target}} \cdot F_{\%}}{9\ \text{kcal/g}}$$
    </div>

    <h3>Clinical Macronutrient Distribution Archetypes</h3>
    <ol class="article-list">
        <li><strong>Balanced Athletic Diet (40% C / 30% P / 30% F):</strong> Optimized for mixed glycolytic and oxidative energy pathway demands in team sports and general fitness.</li>
        <li><strong>High Protein Hypertrophy (35% C / 40% P / 25% F):</strong> Delivers $1.6\text{--}2.2\ \text{g/kg}$ protein to maximize muscle protein synthesis ($\text{MPS}$) and preserve lean mass during hypocaloric dieting.</li>
        <li><strong>Ketogenic Substrate Protocol (5% C / 25% P / 70% F):</strong> Restricts daily carbohydrates below $50\ \text{g}$ to induce hepatic ketogenesis, shifting cellular metabolism toward beta-hydroxybutyrate and acetoacetate oxidation.</li>
    </ol>
</article>
"""

LOG_ARTICLE = r"""
<article class="calculator-article">
    <h2>The Theory of Logarithmic Functions: Napierian Foundations &amp; Computational Applications</h2>
    <p>
        Introduced independently by Scottish mathematician John Napier in 1614 and Swiss clockmaker Joost Bürgi, logarithms fundamentally transformed computational science by converting cumbersome multiplications and divisions into elementary additions and subtractions. In modern analysis, the logarithm is the inverse mathematical operator to exponentiation. It answers the foundational question: to what power must a specified base $b$ be raised to yield a given argument $x$?
    </p>

    <h3>Rigorous Mathematical Definition</h3>
    <p>
        For any positive real base $b \in \mathbb{R}^+$ such that $b \ne 1$, and any strictly positive real argument $x > 0$, the logarithm $y = \log_b(x)$ is uniquely defined by the equivalence relation:
    </p>
    <div class="math-display">
        $$\log_b(x) = y \iff b^y = x$$
    </div>
    <p>
        The function $\log_b: (0, \infty) \to (-\infty, \infty)$ is a continuous, strictly monotonic bijection. When $b > 1$, the function is strictly increasing; when $0 < b < 1$, it is strictly decreasing.
    </p>

    <h3>The Natural Logarithm ($\ln$) &amp; Euler's Number</h3>
    <p>
        The <strong>natural logarithm</strong> employs Euler's transcendental number $e \approx 2.718281828459$ as its base, denoted conventionally as $\ln(x) = \log_e(x)$. In infinitesimal calculus, $\ln(x)$ arises organically as the antiderivative of the reciprocal function:
    </p>
    <div class="math-display">
        $$\ln(x) = \int_{1}^{x} \frac{1}{t} \, dt \quad \text{for } x > 0$$
    </div>
    <p>
        From this integral definition follow the derivative $\frac{d}{dx}\ln(x) = \frac{1}{x}$ and the series expansion around $x = 1$:
    </p>
    <div class="math-display">
        $$\ln(1 + u) = \sum_{k=1}^{\infty} \frac{(-1)^{k-1} u^k}{k} = u - \frac{u^2}{2} + \frac{u^3}{3} - \frac{u^4}{4} + \cdots \quad (|u| \le 1, u \ne -1)$$
    </div>

    <h3>The Change-of-Base Theorem</h3>
    <p>
        A central computational property of logarithmic functions is the <strong>Change-of-Base Theorem</strong>, enabling evaluation of any arbitrary base logarithm through standard natural ($\ln$) or common ($\log_{10}$) algorithms:
    </p>
    <div class="math-display">
        $$\log_b(x) = \frac{\log_k(x)}{\log_k(b)} = \frac{\ln(x)}{\ln(b)} = \frac{\log_{10}(x)}{\log_{10}(b)}$$
    </div>

    <h3>Fundamental Algebraic Laws of Logarithms</h3>
    <ol class="article-list">
        <li><strong>Product Rule:</strong> $\log_b(u \cdot v) = \log_b(u) + \log_b(v)$</li>
        <li><strong>Quotient Rule:</strong> $\log_b\left(\frac{u}{v}\right) = \log_b(u) - \log_b(v)$</li>
        <li><strong>Power Rule:</strong> $\log_b(u^p) = p \cdot \log_b(u)$</li>
        <li><strong>Identity &amp; Zero Points:</strong> $\log_b(b) = 1 \quad \text{and} \quad \log_b(1) = 0$</li>
        <li><strong>Reciprocal Base Inversion:</strong> $\log_b(x) = \frac{1}{\log_x(b)}$</li>
        <li><strong>Exponential Composition:</strong> $b^{\log_b(x)} = x \quad \text{and} \quad \log_b(b^x) = x$</li>
    </ol>

    <h3>Scientific &amp; Engineering Applications</h3>
    <p>
        Because human perception and natural physical phenomena span immense numerical ranges, logarithmic scales are pervasive throughout modern science:
    </p>
    <ul class="article-list">
        <li><strong>Acoustics (Decibels):</strong> Sound pressure level $L_p = 20 \log_{10}\left(\frac{p}{p_0}\right)\ \text{dB}$.</li>
        <li><strong>Seismology (Richter / Moment Magnitude):</strong> Earthquake energy scaling $M_w = \frac{2}{3} \log_{10}(M_0) - 10.7$.</li>
        <li><strong>Chemistry ($\text{pH}$ Acidity):</strong> Hydronium ion concentration $\text{pH} = -\log_{10}[\text{H}_3\text{O}^+]$.</li>
        <li><strong>Computer Science (Information Entropy):</strong> Shannon entropy $H(X) = -\sum p(x_i) \log_2 p(x_i)$ measured in bits/shannons.</li>
    </ul>
</article>
"""

DENSITY_ARTICLE = r"""
<article class="calculator-article">
    <h2>Classical Continuum Mechanics: Physical Density, Specific Gravity &amp; Hydrostatic Equilibrium</h2>
    <p>
        In continuum mechanics and thermodynamics, <strong>mass density</strong> ($\rho$, Greek letter rho) is an intensive physical property of matter that quantifies the quantity of mass contained per unit volume of a homogeneous substance. Unlike extensive thermodynamic quantities such as mass or total internal energy, density is independent of sample size under uniform conditions of temperature and ambient pressure. Density dictates material selection in aerospace engineering, petroleum refining, geological prospecting, and fluid dynamics.
    </p>

    <h3>Fundamental Governing Equation</h3>
    <p>
        For a macroscopic continuum of total mass $m$ occupying a spatial volume $V$, average physical density is defined mathematically as:
    </p>
    <div class="math-display">
        $$\rho = \frac{m}{V}$$
    </div>
    <p>
        In infinitesimal differential notation for heterogeneous spatial distributions where mass varies continuously across a coordinate space $\mathbf{r} \in \mathbb{R}^3$:
    </p>
    <div class="math-display">
        $$\rho(\mathbf{r}) = \lim_{\Delta V \to 0} \frac{\Delta m}{\Delta V} = \frac{dm}{dV} \iff m = \iiint_{\Omega} \rho(\mathbf{r}) \, dV$$
    </div>
    <p>
        The standard International System of Units ($\text{SI}$) unit for density is the kilogram per cubic meter ($\text{kg/m}^3$). Common industrial units include grams per cubic centimeter ($\text{g/cm}^3$, where $1\ \text{g/cm}^3 = 1000\ \text{kg/m}^3$) and imperial pounds per cubic foot ($\text{lb/ft}^3$, where $1\ \text{lb/ft}^3 \approx 16.0185\ \text{kg/m}^3$).
    </p>

    <h3>Specific Gravity (Relative Density)</h3>
    <p>
        <strong>Specific Gravity</strong> ($\text{SG}$), or relative density, is a dimensionless scalar ratio comparing the density of a substance $\rho$ to the reference density of pure, gas-free water $\rho_{\text{H}_2\text{O}}$ at its temperature of maximum density ($3.98^\circ\text{C}$ / $39.2^\circ\text{F}$ at standard atmospheric pressure of $101.325\ \text{kPa}$, where $\rho_{\text{ref}} = 999.972\ \text{kg/m}^3 \approx 1.000\ \text{g/cm}^3$):
    </p>
    <div class="math-display">
        $$\text{SG} = \frac{\rho_{\text{substance}}}{\rho_{\text{ref}}}$$
    </div>
    <p>
        Because $\text{SG}$ is dimensionless, it remains numerically invariant regardless of whether calculations are executed in metric or imperial unit systems.
    </p>

    <h3>Archimedes' Principle &amp; Buoyant Hydrostatic Equilibrium</h3>
    <p>
        Formulated in ancient Syracuse circa 246 BCE, <strong>Archimedes' principle</strong> governs the equilibrium of bodies immersed in a static fluid. Any body completely or partially submerged in a fluid experiences an upward vertical buoyant force $\mathbf{F}_b$ equivalent to the weight of the fluid displaced by the body:
    </p>
    <div class="math-display">
        $$F_b = \rho_{\text{fluid}} \cdot V_{\text{submerged}} \cdot g$$
    </div>
    <p>
        Where $g \approx 9.80665\ \text{m/s}^2$ is the standard acceleration due to terrestrial gravity. Comparing the body's gravitational downward force $F_g = m g = \rho_{\text{body}} V_{\text{total}} g$ against buoyant force establishes three hydrostatic states:
    </p>
    <ul class="article-list">
        <li><strong>Positive Buoyancy (Floating):</strong> When $\rho_{\text{body}} < \rho_{\text{fluid}}$ ($\text{SG} < 1$). The object floats with submerged fraction $\frac{V_{\text{sub}}}{V_{\text{total}}} = \frac{\rho_{\text{body}}}{\rho_{\text{fluid}}} = \text{SG}$.</li>
        <li><strong>Neutral Buoyancy (Suspended):</strong> When $\rho_{\text{body}} = \rho_{\text{fluid}}$ ($\text{SG} = 1$). The object remains static at its current immersion depth.</li>
        <li><strong>Negative Buoyancy (Sinking):</strong> When $\rho_{\text{body}} > \rho_{\text{fluid}}$ ($\text{SG} > 1$). Gravitational weight exceeds peak buoyancy, driving downward acceleration until normal contact forces intervene.</li>
    </ul>

    <h3>Thermodynamic Dependence: Thermal Expansion &amp; Compressibility</h3>
    <p>
        Physical density is intrinsically temperature- and pressure-dependent. For isotropic solids and liquids, volumetric thermal expansion coefficient $\beta$ and isothermal compressibility $\kappa_T$ determine density variations:
    </p>
    <div class="math-display">
        $$\rho(T, P) \approx \rho_0 \left[1 - \beta (T - T_0) + \kappa_T (P - P_0)\right]$$
    </div>
    <p>
        For ideal gases, density couples directly to absolute thermodynamic temperature $T$ and pressure $P$ through the ideal gas law: $\rho = \frac{P \cdot M}{R \cdot T}$, where $M$ is molar mass and $R \approx 8.314\ \text{J/(mol}\cdot\text{K)}$ is the universal gas constant.
    </p>
</article>
"""
