from django.test import TestCase, Client
from django.urls import reverse
from calculators.models import Calculator


class CalculatorNetTests(TestCase):
    def setUp(self):
        self.client = Client()

    def test_home_view(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Free Online Calculators")
        self.assertContains(response, "calculator-search")
        self.assertContains(response, "brand-logo-img")
        self.assertContains(response, "theme-toggle-btn")
        self.assertContains(response, "ad-top-banner")
        self.assertContains(response, "ad-sidebar")
        self.assertContains(response, "ad-bottom-content")

    def test_bmi_calculator_view(self):
        response = self.client.get(reverse('bmi_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "BMI Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/bmi.js")
        self.assertNotContains(response, "js/loan.js")
        # Dynamic database model verification
        calc = Calculator.objects.filter(slug='bmi-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Body Mass Index", calc.article_content)
        self.assertContains(response, "What is Body Mass Index (BMI)?")

    def test_loan_calculator_view(self):
        response = self.client.get(reverse('loan_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Loan Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/loan.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='loan-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("What is a Loan Calculator?", calc.article_content)

    def test_percentage_calculator_view(self):
        response = self.client.get(reverse('percentage_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Percentage Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/percentage.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='percentage-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Three Core Mathematical Percentage Formulas", calc.article_content)

    def test_mortgage_calculator_view(self):
        response = self.client.get(reverse('mortgage_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Mortgage Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/mortgage.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='mortgage-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Monthly Mortgage Payments", calc.article_content)
        self.assertContains(response, "What is a Mortgage Calculator?")

    def test_calorie_calculator_view(self):
        response = self.client.get(reverse('calorie_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Calorie Needs Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/calorie.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='calorie-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Mifflin-St Jeor BMR Equation", calc.article_content)
        self.assertContains(response, "What is a Calorie Needs Calculator?")

    def test_scientific_calculator_view(self):
        response = self.client.get(reverse('scientific_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Scientific Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/scientific.js")
        self.assertNotContains(response, "js/percentage.js")
        calc = Calculator.objects.filter(slug='scientific-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Trigonometric and Inverse Trigonometric Functions", calc.article_content)
        self.assertContains(response, "What is a Scientific Calculator?")

    def test_age_calculator_view(self):
        response = self.client.get(reverse('age_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Age Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/age.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='age-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Gregorian Leap Year Determination Rule", calc.article_content)
        self.assertContains(response, "What is an Age Calculator?")

    def test_auto_loan_calculator_view(self):
        response = self.client.get(reverse('auto_loan_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Auto Loan Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/auto_loan.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='auto-loan-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Monthly Auto Payment Equation", calc.article_content)
        self.assertContains(response, "What is an Auto Loan Calculator?")

    def test_body_fat_calculator_view(self):
        response = self.client.get(reverse('body_fat_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Body Fat Percentage Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/body_fat.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='body-fat-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("U.S. Navy Circumference Method Formulas", calc.article_content)
        self.assertContains(response, "What is a Body Fat Percentage Calculator?")

    def test_fraction_calculator_view(self):
        response = self.client.get(reverse('fraction_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Fraction Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/fraction.js")
        self.assertNotContains(response, "js/percentage.js")
        calc = Calculator.objects.filter(slug='fraction-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Addition and Subtraction", calc.article_content)
        self.assertContains(response, "What is a Fraction Calculator?")

    def test_date_difference_calculator_view(self):
        response = self.client.get(reverse('date_difference_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Date Difference Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/date_diff.js")
        self.assertNotContains(response, "js/age.js")
        calc = Calculator.objects.filter(slug='date-difference-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Absolute Continuous Day Difference", calc.article_content)
        self.assertContains(response, "What is a Date Difference Calculator?")

    def test_compound_interest_calculator_view(self):
        response = self.client.get(reverse('compound_interest_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Compound Interest Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/compound_interest.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='compound-interest-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Understanding Compound Interest", calc.article_content)
        self.assertContains(response, "The Mathematical Engine of Wealth")

    def test_bmr_calculator_view(self):
        response = self.client.get(reverse('bmr_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Basal Metabolic Rate (BMR) Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/bmr.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='bmr-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Basal Metabolic Rate (BMR)", calc.article_content)
        self.assertContains(response, "Mifflin-St Jeor")

    def test_binary_hex_converter_view(self):
        response = self.client.get(reverse('binary_hex_converter'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Binary &amp; Hexadecimal Converter")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/binary_hex.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='binary-hex-converter').first()
        self.assertIsNotNone(calc)
        self.assertIn("Positional Number Systems", calc.article_content)
        self.assertContains(response, "Interactive Bit Matrix")

    def test_time_duration_calculator_view(self):
        response = self.client.get(reverse('time_duration_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Time &amp; Duration Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/time_duration.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='time-duration-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Time and Duration Arithmetic", calc.article_content)
        self.assertContains(response, "Sexagesimal Mechanics")

    def test_amortization_calculator_view(self):
        response = self.client.get(reverse('amortization_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Amortization Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/amortization.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='amortization-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("The Mathematics of Loan Amortization", calc.article_content)

    def test_ideal_weight_calculator_view(self):
        response = self.client.get(reverse('ideal_weight_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Ideal Body Weight Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/ideal_weight.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='ideal-weight-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Devine Formula", calc.article_content)

    def test_decimal_to_fraction_calculator_view(self):
        response = self.client.get(reverse('decimal_to_fraction_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Decimal to Fraction Converter")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/decimal_to_fraction.js")
        self.assertNotContains(response, "js/percentage.js")
        calc = Calculator.objects.filter(slug='decimal-to-fraction-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Euclidean Algorithm", calc.article_content)

    def test_work_hours_calculator_view(self):
        response = self.client.get(reverse('work_hours_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Work Hours &amp; Timesheet Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/work_hours.js")
        self.assertNotContains(response, "js/time_duration.js")
        calc = Calculator.objects.filter(slug='work-hours-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Overtime Remuneration Models", calc.article_content)

    def test_refinance_calculator_view(self):
        response = self.client.get(reverse('refinance_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Refinance Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/refinance.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='refinance-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Break-Even", calc.article_content)

    def test_running_pace_calculator_view(self):
        response = self.client.get(reverse('running_pace_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Running Pace Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/running_pace.js")
        self.assertNotContains(response, "js/calorie.js")
        calc = Calculator.objects.filter(slug='running-pace-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Pete Riegel", calc.article_content)

    def test_graphing_calculator_view(self):
        response = self.client.get(reverse('graphing_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "2D Function Graphing Tool")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/graphing.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='graphing-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Affine World-to-Screen", calc.article_content)

    def test_gpa_calculator_view(self):
        response = self.client.get(reverse('gpa_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "College GPA Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/gpa.js")
        self.assertNotContains(response, "js/age.js")
        calc = Calculator.objects.filter(slug='gpa-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Academic Quality Point Systems", calc.article_content)

    def test_retirement_calculator_view(self):
        response = self.client.get(reverse('retirement_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Retirement Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/retirement.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='retirement-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Compound Accumulation Phase", calc.article_content)

    def test_target_heart_rate_calculator_view(self):
        response = self.client.get(reverse('target_heart_rate_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Target Heart Rate Zones")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/target_heart_rate.js")
        self.assertNotContains(response, "js/calorie.js")
        calc = Calculator.objects.filter(slug='target-heart-rate-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Karvonen Heart Rate Reserve", calc.article_content)

    def test_matrix_calculator_view(self):
        response = self.client.get(reverse('matrix_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Matrix Operations Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/matrix.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='matrix-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Computational Linear Algebra", calc.article_content)

    def test_final_grade_calculator_view(self):
        response = self.client.get(reverse('final_grade_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Final Grade Needed Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/final_grade.js")
        self.assertNotContains(response, "js/gpa.js")
        calc = Calculator.objects.filter(slug='final-grade-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Academic Grading Analytics", calc.article_content)

    def test_investment_calculator_view(self):
        response = self.client.get(reverse('investment_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Investment Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/investment.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='investment-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Compound Capital Accumulation Models", calc.article_content)

    def test_pregnancy_calculator_view(self):
        response = self.client.get(reverse('pregnancy_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Pregnancy Due Date Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/pregnancy.js")
        self.assertNotContains(response, "js/calorie.js")
        calc = Calculator.objects.filter(slug='pregnancy-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Gestational Biometrics", calc.article_content)

    def test_random_number_generator_view(self):
        response = self.client.get(reverse('random_number_generator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Random Number Generator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/random_number.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='random-number-generator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Linear Congruential Recurrence", calc.article_content)

    def test_subnet_calculator_view(self):
        response = self.client.get(reverse('subnet_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "IPv4 Subnet Mask Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/subnet.js")
        self.assertNotContains(response, "js/time_duration.js")
        calc = Calculator.objects.filter(slug='subnet-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Boolean Algebraic Network", calc.article_content)

    def test_inflation_calculator_view(self):
        response = self.client.get(reverse('inflation_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Inflation Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/inflation.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='inflation-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Consumer Price Index", calc.article_content)

    def test_ovulation_calculator_view(self):
        response = self.client.get(reverse('ovulation_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Ovulation &amp; Fertility Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/ovulation.js")
        self.assertNotContains(response, "js/calorie.js")
        calc = Calculator.objects.filter(slug='ovulation-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Reproductive Physiology", calc.article_content)

    def test_standard_deviation_calculator_view(self):
        response = self.client.get(reverse('standard_deviation_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Standard Deviation &amp; Variance Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/standard_deviation.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='standard-deviation-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Bessel's Correction", calc.article_content)

    def test_speed_distance_time_calculator_view(self):
        response = self.client.get(reverse('speed_distance_time_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Speed, Distance &amp; Time Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/speed_distance_time.js")
        self.assertNotContains(response, "js/time_duration.js")
        calc = Calculator.objects.filter(slug='speed-distance-time-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Harmonic Mean Average Speed", calc.article_content)

    def test_salary_to_hourly_calculator_view(self):
        response = self.client.get(reverse('salary_to_hourly_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Salary to Hourly Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/salary_to_hourly.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='salary-to-hourly-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Labor Economics", calc.article_content)

    def test_lean_body_mass_calculator_view(self):
        response = self.client.get(reverse('lean_body_mass_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Lean Body Mass Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/lean_body_mass.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='lean-body-mass-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Boer Formula", calc.article_content)

    def test_right_triangle_solver_view(self):
        response = self.client.get(reverse('right_triangle_solver'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Right Triangle Solver")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/right_triangle.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='right-triangle-solver').first()
        self.assertIsNotNone(calc)
        self.assertIn("Pythagorean Theorem", calc.article_content)

    def test_tip_calculator_view(self):
        response = self.client.get(reverse('tip_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Tip &amp; Split Bill Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/tip.js")
        self.assertNotContains(response, "js/work_hours.js")
        calc = Calculator.objects.filter(slug='tip-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Microeconomics of Gratuity", calc.article_content)

    def test_income_tax_calculator_view(self):
        response = self.client.get(reverse('income_tax_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Income Tax Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/income_tax.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='income-tax-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Progressive Income Taxation", calc.article_content)

    def test_water_intake_calculator_view(self):
        response = self.client.get(reverse('water_intake_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Daily Water Intake Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/water_intake.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='water-intake-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Human Hydration Physiology", calc.article_content)

    def test_exponent_calculator_view(self):
        response = self.client.get(reverse('exponent_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Exponent &amp; Power Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/exponent.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='exponent-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Laws of Exponentiation", calc.article_content)

    def test_fuel_cost_calculator_view(self):
        response = self.client.get(reverse('fuel_cost_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Fuel Cost &amp; Mileage Trip Planner")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/fuel_cost.js")
        self.assertNotContains(response, "js/speed_distance_time.js")
        calc = Calculator.objects.filter(slug='fuel-cost-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Vehicular Energy Consumption", calc.article_content)

    def test_cd_calculator_view(self):
        response = self.client.get(reverse('cd_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Certificate of Deposit")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/cd.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='cd-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Certificate of Deposit", calc.article_content)

    def test_macro_calculator_view(self):
        response = self.client.get(reverse('macro_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Macronutrient Ratio Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/macro.js")
        self.assertNotContains(response, "js/calorie.js")
        calc = Calculator.objects.filter(slug='macro-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Macronutrient", calc.article_content)

    def test_log_calculator_view(self):
        response = self.client.get(reverse('log_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Logarithm Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/logarithm.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='log-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Logarithm", calc.article_content)

    def test_density_calculator_view(self):
        response = self.client.get(reverse('density_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Physical Density Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/density.js")
        self.assertNotContains(response, "js/speed_distance_time.js")
        calc = Calculator.objects.filter(slug='density-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Physical Density", calc.article_content)

    def test_four_zero_one_k_calculator_view(self):
        response = self.client.get(reverse('four_zero_one_k_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "401(k) Retirement Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/four_zero_one_k.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='401k-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Fundamentals of 401(k)", calc.article_content)

    def test_sleep_calculator_view(self):
        response = self.client.get(reverse('sleep_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Sleep Cycle Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/sleep.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='sleep-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Chronobiology and Ultradian", calc.article_content)

    def test_permutations_combinations_calculator_view(self):
        response = self.client.get(reverse('permutations_combinations_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Permutations &amp; Combinations")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/permutations_combinations.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='permutations-combinations-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Combinatorial Analysis", calc.article_content)

    def test_force_calculator_view(self):
        response = self.client.get(reverse('force_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Newton Force Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/force.js")
        self.assertNotContains(response, "js/speed_distance_time.js")
        calc = Calculator.objects.filter(slug='force-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Newton's Second Law", calc.article_content)

    def test_annuity_payout_calculator_view(self):
        response = self.client.get(reverse('annuity_payout_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Annuity Payout Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/annuity.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='annuity-payout-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Actuarial Mathematics", calc.article_content)

    def test_army_body_fat_calculator_view(self):
        response = self.client.get(reverse('army_body_fat_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Army Body Fat Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/army_body_fat.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='army-body-fat-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("AR 600-9", calc.article_content)

    def test_mean_median_mode_calculator_view(self):
        response = self.client.get(reverse('mean_median_mode_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Mean, Median &amp; Mode Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/mean_median_mode.js")
        self.assertNotContains(response, "js/standard_deviation.js")
        calc = Calculator.objects.filter(slug='mean-median-mode-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Measures of Central Tendency", calc.article_content)

    def test_power_converter_view(self):
        response = self.client.get(reverse('power_converter'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Power &amp; Wattage Converter")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/power_converter.js")
        self.assertNotContains(response, "js/force.js")
        calc = Calculator.objects.filter(slug='power-converter').first()
        self.assertIsNotNone(calc)
        self.assertIn("Physics of Power", calc.article_content)

    def test_apr_vs_apy_calculator_view(self):
        response = self.client.get(reverse('apr_vs_apy_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "APR vs APY Calculator")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/apr_apy.js")
        self.assertNotContains(response, "js/loan.js")
        calc = Calculator.objects.filter(slug='apr-vs-apy-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Mathematical Definition of Nominal APR", calc.article_content)

    def test_bac_calculator_view(self):
        response = self.client.get(reverse('bac_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Blood Alcohol Content (BAC)")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/bac.js")
        self.assertNotContains(response, "js/bmi.js")
        calc = Calculator.objects.filter(slug='bac-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Classical Widmark Kinetic Equation", calc.article_content)

    def test_quadratic_formula_calculator_view(self):
        response = self.client.get(reverse('quadratic_formula_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Quadratic Equation Solver")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/quadratic.js")
        self.assertNotContains(response, "js/scientific.js")
        calc = Calculator.objects.filter(slug='quadratic-formula-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Rigorous Derivation of the Quadratic Formula", calc.article_content)

    def test_energy_calculator_view(self):
        response = self.client.get(reverse('energy_calculator'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Kinetic &amp; Potential Energy")
        self.assertContains(response, "katex.min.css")
        self.assertContains(response, "js/energy.js")
        self.assertNotContains(response, "js/force.js")
        calc = Calculator.objects.filter(slug='kinetic-potential-energy-calculator').first()
        self.assertIsNotNone(calc)
        self.assertIn("Translational Kinetic Energy", calc.article_content)

    def test_html_sitemap_view(self):
        response = self.client.get(reverse('html_sitemap'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Financial Calculators")
        self.assertContains(response, "Fitness & Health")
        self.assertContains(response, "Math Calculators")
        self.assertContains(response, "Other Calculators")
        self.assertContains(response, "mortgage-calculator")
        self.assertContains(response, "calorie-calculator")
        self.assertContains(response, "scientific-calculator")
        self.assertContains(response, "age-calculator")
        self.assertContains(response, "auto-loan-calculator")
        self.assertContains(response, "body-fat-calculator")
        self.assertContains(response, "fraction-calculator")
        self.assertContains(response, "date-difference-calculator")
        self.assertContains(response, "compound-interest-calculator")
        self.assertContains(response, "bmr-calculator")
        self.assertContains(response, "binary-hex-converter")
        self.assertContains(response, "time-duration-calculator")
        self.assertContains(response, "amortization-calculator")
        self.assertContains(response, "ideal-weight-calculator")
        self.assertContains(response, "decimal-to-fraction-calculator")
        self.assertContains(response, "work-hours-calculator")
        self.assertContains(response, "refinance-calculator")
        self.assertContains(response, "running-pace-calculator")
        self.assertContains(response, "graphing-calculator")
        self.assertContains(response, "gpa-calculator")
        self.assertContains(response, "retirement-calculator")
        self.assertContains(response, "target-heart-rate-calculator")
        self.assertContains(response, "matrix-calculator")
        self.assertContains(response, "final-grade-calculator")
        self.assertContains(response, "investment-calculator")
        self.assertContains(response, "pregnancy-calculator")
        self.assertContains(response, "random-number-generator")
        self.assertContains(response, "subnet-calculator")
        self.assertContains(response, "inflation-calculator")
        self.assertContains(response, "ovulation-calculator")
        self.assertContains(response, "standard-deviation-calculator")
        self.assertContains(response, "speed-distance-time-calculator")
        self.assertContains(response, "salary-to-hourly-calculator")
        self.assertContains(response, "lean-body-mass-calculator")
        self.assertContains(response, "right-triangle-solver")
        self.assertContains(response, "tip-calculator")
        self.assertContains(response, "income-tax-calculator")
        self.assertContains(response, "daily-water-intake-calculator")
        self.assertContains(response, "exponent-power-calculator")
        self.assertContains(response, "fuel-cost-calculator")
        self.assertContains(response, "cd-calculator")
        self.assertContains(response, "macronutrient-calculator")
        self.assertContains(response, "logarithm-calculator")
        self.assertContains(response, "density-calculator")
        self.assertContains(response, "401k-calculator")
        self.assertContains(response, "sleep-calculator")
        self.assertContains(response, "permutations-combinations-calculator")
        self.assertContains(response, "force-calculator")

    def test_xml_sitemap_view(self):
        # Trigger calculator creation first
        self.client.get(reverse('bmi_calculator'))
        self.client.get(reverse('loan_calculator'))
        self.client.get(reverse('percentage_calculator'))
        self.client.get(reverse('mortgage_calculator'))
        self.client.get(reverse('calorie_calculator'))
        self.client.get(reverse('scientific_calculator'))
        self.client.get(reverse('age_calculator'))
        self.client.get(reverse('auto_loan_calculator'))
        self.client.get(reverse('body_fat_calculator'))
        self.client.get(reverse('fraction_calculator'))
        self.client.get(reverse('date_difference_calculator'))
        self.client.get(reverse('compound_interest_calculator'))
        self.client.get(reverse('bmr_calculator'))
        self.client.get(reverse('binary_hex_converter'))
        self.client.get(reverse('time_duration_calculator'))
        self.client.get(reverse('amortization_calculator'))
        self.client.get(reverse('ideal_weight_calculator'))
        self.client.get(reverse('decimal_to_fraction_calculator'))
        self.client.get(reverse('work_hours_calculator'))
        self.client.get(reverse('refinance_calculator'))
        self.client.get(reverse('running_pace_calculator'))
        self.client.get(reverse('graphing_calculator'))
        self.client.get(reverse('gpa_calculator'))
        self.client.get(reverse('retirement_calculator'))
        self.client.get(reverse('target_heart_rate_calculator'))
        self.client.get(reverse('matrix_calculator'))
        self.client.get(reverse('final_grade_calculator'))
        self.client.get(reverse('investment_calculator'))
        self.client.get(reverse('pregnancy_calculator'))
        self.client.get(reverse('random_number_generator'))
        self.client.get(reverse('subnet_calculator'))
        self.client.get(reverse('inflation_calculator'))
        self.client.get(reverse('ovulation_calculator'))
        self.client.get(reverse('standard_deviation_calculator'))
        self.client.get(reverse('speed_distance_time_calculator'))
        self.client.get(reverse('salary_to_hourly_calculator'))
        self.client.get(reverse('lean_body_mass_calculator'))
        self.client.get(reverse('right_triangle_solver'))
        self.client.get(reverse('tip_calculator'))
        self.client.get(reverse('income_tax_calculator'))
        self.client.get(reverse('water_intake_calculator'))
        self.client.get(reverse('exponent_calculator'))
        self.client.get(reverse('fuel_cost_calculator'))
        self.client.get(reverse('cd_calculator'))
        self.client.get(reverse('macro_calculator'))
        self.client.get(reverse('log_calculator'))
        self.client.get(reverse('density_calculator'))
        self.client.get(reverse('four_zero_one_k_calculator'))
        self.client.get(reverse('sleep_calculator'))
        self.client.get(reverse('permutations_combinations_calculator'))
        self.client.get(reverse('force_calculator'))
        self.client.get(reverse('annuity_payout_calculator'))
        self.client.get(reverse('army_body_fat_calculator'))
        self.client.get(reverse('mean_median_mode_calculator'))
        self.client.get(reverse('power_converter'))
        self.client.get(reverse('apr_vs_apy_calculator'))
        self.client.get(reverse('bac_calculator'))
        self.client.get(reverse('quadratic_formula_calculator'))
        self.client.get(reverse('energy_calculator'))

        response = self.client.get('/sitemap.xml')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response['content-type'], 'application/xml')
        self.assertContains(response, "bmi-calculator")
        self.assertContains(response, "loan-calculator")
        self.assertContains(response, "percentage-calculator")
        self.assertContains(response, "mortgage-calculator")
        self.assertContains(response, "calorie-calculator")
        self.assertContains(response, "scientific-calculator")
        self.assertContains(response, "age-calculator")
        self.assertContains(response, "auto-loan-calculator")
        self.assertContains(response, "body-fat-calculator")
        self.assertContains(response, "fraction-calculator")
        self.assertContains(response, "date-difference-calculator")
        self.assertContains(response, "compound-interest-calculator")
        self.assertContains(response, "bmr-calculator")
        self.assertContains(response, "binary-hex-converter")
        self.assertContains(response, "time-duration-calculator")
        self.assertContains(response, "amortization-calculator")
        self.assertContains(response, "ideal-weight-calculator")
        self.assertContains(response, "decimal-to-fraction-calculator")
        self.assertContains(response, "work-hours-calculator")
        self.assertContains(response, "refinance-calculator")
        self.assertContains(response, "running-pace-calculator")
        self.assertContains(response, "graphing-calculator")
        self.assertContains(response, "gpa-calculator")
        self.assertContains(response, "retirement-calculator")
        self.assertContains(response, "target-heart-rate-calculator")
        self.assertContains(response, "matrix-calculator")
        self.assertContains(response, "final-grade-calculator")
        self.assertContains(response, "investment-calculator")
        self.assertContains(response, "pregnancy-calculator")
        self.assertContains(response, "random-number-generator")
        self.assertContains(response, "subnet-calculator")
        self.assertContains(response, "inflation-calculator")
        self.assertContains(response, "ovulation-calculator")
        self.assertContains(response, "standard-deviation-calculator")
        self.assertContains(response, "speed-distance-time-calculator")
        self.assertContains(response, "salary-to-hourly-calculator")
        self.assertContains(response, "lean-body-mass-calculator")
        self.assertContains(response, "right-triangle-solver")
        self.assertContains(response, "tip-calculator")
        self.assertContains(response, "income-tax-calculator")
        self.assertContains(response, "daily-water-intake-calculator")
        self.assertContains(response, "exponent-power-calculator")
        self.assertContains(response, "fuel-cost-calculator")
        self.assertContains(response, "cd-calculator")
        self.assertContains(response, "macronutrient-calculator")
        self.assertContains(response, "logarithm-calculator")
        self.assertContains(response, "density-calculator")
        self.assertContains(response, "401k-calculator")
        self.assertContains(response, "sleep-calculator")
        self.assertContains(response, "permutations-combinations-calculator")
        self.assertContains(response, "force-calculator")
        self.assertContains(response, "annuity-payout-calculator")
        self.assertContains(response, "army-body-fat-calculator")
        self.assertContains(response, "mean-median-mode-calculator")
        self.assertContains(response, "power-converter")
        self.assertContains(response, "apr-vs-apy-calculator")
        self.assertContains(response, "bac-calculator")
        self.assertContains(response, "quadratic-formula-calculator")
        self.assertContains(response, "kinetic-potential-energy-calculator")

    def test_robots_txt_view(self):
        response = self.client.get('/robots.txt')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response['content-type'], 'text/plain; charset=utf-8')
        self.assertContains(response, "User-agent: *")
        self.assertContains(response, "Allow: /")
        self.assertContains(response, "Sitemap:")
        self.assertContains(response, "sitemap.xml")

    def test_info_pages(self):
        for name in ['about', 'terms', 'privacy', 'contact']:
            resp = self.client.get(reverse(name))
            self.assertEqual(resp.status_code, 200)
        # Verify contact email in contact page
        contact_resp = self.client.get(reverse('contact'))
        self.assertContains(contact_resp, "ssk.nsm313@gmail.com")

    def test_ads_txt_view(self):
        response = self.client.get('/ads.txt')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response['content-type'], 'text/plain; charset=utf-8')
        self.assertContains(response, "pub-8130506129253566")


