# Generated by Django 5.2.17 on 2026-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Calculator display title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug identifier', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('financial', 'Financial Calculators'), ('fitness-and-health', 'Fitness and Health Calculators'), ('math', 'Math Calculators'), ('other', 'Other Calculators')], default='other', max_length=50)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Meta Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta Description')),
                ('article_content', models.TextField(help_text='Comprehensive SEO article content in HTML with KaTeX formulas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculator',
                'verbose_name_plural': 'Calculators',
                'ordering': ['title'],
            },
        ),
    ]
